notifications:
  email: false

language: node_js

node_js:
  - '6.5.0'
  - 'iojs'

install:
    - npm install

script:
  - npm test

after_success:
  - npm i coveralls
  - cat coverage/lcov.info | node_modules/.bin/coveralls
